export const SCREENS = {
  stacks: {
    Customer: "Customer_Navigator",
    Collector: "Collector_Navigator",
  },
  Login: "Login_Screen",
  Onboarding: "Onboarding_Screen",
  Register: "Register_Screen",
  ForgotPass: "Forgot_Password_Screen",
  CustomerDashboard: "Customer_Dashboard",
  CollectorDashboard: "Collector_dashboard",
  WelcomeInScreen: "Welcome_in_screen",
  ProfileUpdateModal: "Update_profile_modal",
  CustomerRequest: "Customer_request",
  CustomerViewRequests: "Customer_view_requests",
  CustomerTracking: "Customer_tracking",
  CollectorRequest: "Collector_request",
  CollectorViewRequests: "Collector_view_requests",
  CollectorTracking: "Collector_tracking",
  CollectorCompleted: "Collector_Completeds",
  Support: "Support",
  Settings: "Settings",
  Address: "Address",
};
